{-# LANGUAGE QuasiQuotes #-}
{-# LANGUAGE ViewPatterns #-}

-- | Copyright : (c) Crown Copyright GCHQ
module Bootstrap.Data.Bootstrappable.Rust.CargoLock
  ( CargoLock,
    cargoLockFor,
  )
where

import Bootstrap.Data.Bootstrappable
  ( Bootstrappable (bootstrapContent, bootstrapName, bootstrapReason),
  )
import Bootstrap.Data.ProjectName (ProjectName (unProjectName))
import Bootstrap.Data.ProjectType
  ( ProjectType (Rust),
  )
import Text.RawString.QQ (r)

newtype CargoLock = CargoLock ProjectName

instance Bootstrappable CargoLock where
  bootstrapName = const "Cargo.lock"
  bootstrapReason = const "The locked dependencies of your rust project"
  bootstrapContent (CargoLock (unProjectName -> n)) =
    pure . Right $
      [r|# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 3

[[package]]
name = "|]
        <> n
        <> [r|"
version = "0.1.0"
|]

cargoLockFor :: ProjectType -> ProjectName -> Maybe CargoLock
cargoLockFor = \case
  Rust -> Just . CargoLock
  _ -> const Nothing
