# © Crown Copyright GCHQ

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
name: nix-bootstrap
version: 2.3.0.4
author: gchquser
maintainer: 48051938+sd234678@users.noreply.github.com
copyright: Crown Copyright
license: Apache-2.0
default-extensions:
  - BlockArguments
  - DerivingStrategies
  - GADTs
  - LambdaCase
  - NamedFieldPuns
  - OverloadedStrings
  - RecordWildCards
  - StrictData
dependencies:
  - name: base
    version: "== 4.19.2.0"
    mixin:
      - hiding (Prelude)
  - relude == 1.2.2.0
flags:
  prod:
    default: false
    description: Enable production defaults
    manual: true
ghc-options:
  - "-Wall"
  - "-Wcpp-undef"
  - "-Widentities"
  - "-Wincomplete-patterns"
  - "-Wincomplete-record-updates"
  - "-Wincomplete-uni-patterns"
  - "-Wmissing-deriving-strategies"
  - "-Wmissing-export-lists"
  - "-Wmissing-import-lists"
  - "-Wmissing-signatures"
  - "-Wpartial-fields"
  - "-Wredundant-constraints"
when:
  - condition: flag(prod)
    ghc-options:
      - "-O2"
      - "-Werror"
library:
  source-dirs: src
  dependencies:
    - aeson == 2.2.3.0
    - aeson-pretty == 0.8.10
    - blaze-html == 0.9.2.0
    - directory == 1.3.8.5
    - dhall == 1.42.2
    - exceptions == 0.10.7
    - extra == 1.7.16
    - filepath == 1.4.301.0
    - lens == 5.3.4
    - megaparsec == 9.7.0
    - mtl == 2.3.1
    - parser-combinators == 1.3.0
    - process == 1.6.25.0
    - raw-strings-qq == 1.1
    - regex-compat == 0.95.2.2
    - silently == 1.2.5.4
    - singletons == 3.0.4
    - template-haskell == 2.21.0.0
    - terminal == 0.2.0.0
    - th-abstraction == 0.7.1.0
    - tomland == 1.3.3.3
    - which == 0.2.0.3
    - yaml == 0.11.11.2
executables:
  app:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - "-O2"
      - "-threaded"
      - "-rtsopts"
      - "-with-rtsopts=-N"
    dependencies:
      - nix-bootstrap
tests:
  nix-bootstrap-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - dhall == 1.42.2
      - hspec == 2.11.12
      - hspec-expectations-pretty-diff == 0.7.2.6
      - nix-bootstrap
      - QuickCheck == 2.14.3
      - raw-strings-qq == 1.1
      - tomland == 1.3.3.3
    build-tools:
      - hspec-discover == 2.11.12
