# © Crown Copyright GCHQ
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

["async"]
cve = ["CVE-2021-43138"]
comment = "CVE refers to the JavaScript package async, not this haskell package."

["bash"]
comment = "bash is only a build-time dependency so we're not vulnerable to this attack."

["binutils"]
comment = "binutils is only a build-time dependency so we're not vulnerable to this attack."

["cereal"]
cve = ["CVE-2020-11104", "CVE-2020-11105"]
comment = "CVEs refer to the C++ library cereal, not this haskell package."

["cookie"]
cve = ["CVE-2017-18589"]
comment = "CVEs refer to the Rust library cereal, not this haskell package."

["curl"]
comment = "curl is only a build-time dependency so we're not vulnerable to this attack."

["flex"]
cve = ["CVE-2019-6293"]
comment = """Upstream decided not to patch this bug as there is no \
  security issue; just a potential for a crash if extremely large \
  YAML files are used. This is not expected to occur in nix-bootstrap.\
  """

["fuse"]
cve = ["CVE-2019-14860", "CVE-2019-14900"]
comment = "CVEs refer to RedHat Fuse, not C libfuse (Filesystem in Userspace) on which we depend."

["git"]
comment = """Git is only a build-time dependency of the project; it is the responsibility of users \
  to ensure their version of git is up-to-date.\
  """

["hedgehog"]
cve = ["CVE-2021-4276"]
comment = "CVE refers to dns-stats/hedgehog, not this package."

["http-client"]
cve = ["CVE-2020-11021"]
comment = "CVE refers to the JavaScript package @actions/http-client, not this haskell package."

["lens"]
cve = ["CVE-2021-23154", "CVE-2021-44458"]
comment = "CVEs refer to Mirantis Lens, not this haskell package."

["libarchive"]
cve = ["CVE-2022-36227"]
comment = "libarchive is only a build-time dependency so we are not vulnerable to this attack."

["libxml2"]
comment = "libxml2 is only a build-time dependency so we're not vulnerable to this attack."

["libxslt-1.1.35"]
cve = ["CVE-2022-29824"]
comment = """No upstream fix yet, but exploitation requires a victim \
  to open a crafted, multi-gigabyte XML file, so considered unlikely.\
  """

["linux-pam"]
cve = ["CVE-2022-28321"]
comment = "Only affects OpenSUSE distributions"

["network"]
cve = ["CVE-2021-35048",
  "CVE-2021-35047",
  "CVE-2021-35049",
  "CVE-2021-35050",
  "CVE-2022-24388",
  "CVE-2022-24389",
  "CVE-2022-24390",
  "CVE-2022-24391",
  "CVE-2022-24392",
  "CVE-2022-24393",
  "CVE-2022-24394",
  "CVE-2022-0486",
  "CVE-2022-0997"]
comment = "CVEs refer to Fidelis Network, not this haskell package."

["openssl"]
comment = "openssl is only a build-time dependency so we are not vulnerable to this attack."

["patch"]
comment = "patch is only a build-time dependency so we are not vulnerable to this attack."

["safe"]
comment = "CVEs refer to F-Secure SAFE browser, not this haskell package."

["setuptools"]
comment = "setuptools is only a build-time dependency so we are not vulnerable to this attack."

["shadow"]
cve = ["CVE-2016-15024"]
comment = "CVE refers to doomsider/shadow, not these shadow utils."

["sqlite"]
comment = "sqlite is only a build-time dependency so we're not vulnerable to this attack."

["tar-0.5.1.1"]
comment = "CVEs refer to either node-tar or GNU tar, not this haskell package."

["tar-0.5.1.1-r5.cabal"]
comment = "CVEs refer to either node-tar or GNU tar, not this haskell package."

["tcl-8.6.11"]
cve = ["CVE-2021-35331"]
comment = """Severity disputed and upstream patch not yet in nixpkgs. \
  Unfeasible to fix locally as it would require complete rebuild of all haskell packages.\
  """

["terminal"]
cve = ["CVE-2022-44702"]
comment = "CVE refers to microsoft terminal, not this haskell package."

["unzip"]
cve = ["CVE-2021-4217", "CVE-2022-0529", "CVE-2022-0530"]
comment = "None of these vulnerabilities affect nix-bootstrap as it doesn't process arbitrary zip files."

["wheel"]
comment = "wheel is only a build-time dependency so we are not vulnerable to this attack."

["yaml"]
cve = ["CVE-2022-3064", "CVE-2021-4235"]
comment = "CVEs refer to go-yaml, not this haskell package."

["zlib-0.6.3.0"]
cve = ["CVE-2018-25032", "CVE-2022-37434"]
comment = "Actual zlib dependency is already on a patched version; this version is a haskell library."

["zlib-1.2.12"]
cve = ["CVE-2022-37434"]
comment = "We do not call the affected code with untrusted data."
