{-# LANGUAGE QuasiQuotes #-}

-- | Copyright : (c) Crown Copyright GCHQ
module Bootstrap.Data.Bootstrappable.Rust.CargoLockSpec (spec) where

import Bootstrap.Data.Bootstrappable (Bootstrappable (bootstrapContent))
import Bootstrap.Data.Bootstrappable.Rust.CargoLock
  ( cargoLockFor,
  )
import Bootstrap.Data.ProjectName (mkProjectName)
import Bootstrap.Data.ProjectType
  ( ProjectType (Rust),
  )
import qualified Relude.Unsafe as Unsafe
import Test.Hspec (Spec, describe, it)
import Test.Hspec.Expectations.Pretty (shouldBe)
import Text.RawString.QQ (r)

spec :: Spec
spec = describe "Cargo.lock rendering" do
  it "renders correctly" do
    bootstrapContent (cargoLockFor Rust . Unsafe.fromJust $ mkProjectName "test-project")
      >>= ( `shouldBe`
              Right
                [r|# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 3

[[package]]
name = "test-project"
version = "0.1.0"
|]
          )
