{-# LANGUAGE QuasiQuotes #-}
{-# LANGUAGE TemplateHaskellQuotes #-}

-- | Copyright : (c) Crown Copyright GCHQ
module Bootstrap.Nix.Expr.Nixpkgs (nixpkgsFromIntermediateFlake, nixpkgsFromNiv) where

import Bootstrap.Nix.Expr (Expr, nix)

-- | An expression which imports nixpkgs from the flake.lock generated by the intermediate flake
nixpkgsFromIntermediateFlake :: Expr
nixpkgsFromIntermediateFlake =
  [nix|
  let lock = builtins.fromJSON (builtins.readFile ./flake.lock);
  in import (builtins.fetchTarball {
    url = "https://github.com/NixOS/nixpkgs/tarball/${lock.nodes.nixpkgs-src.locked.rev}";
    sha256 = lock.nodes.nixpkgs-src.locked.narHash;
  }) {}|]

-- | An expression which imports nixpkgs from the sources.nix provided by niv
nixpkgsFromNiv :: Expr
nixpkgsFromNiv = [nix|import (import nix/sources.nix).nixpkgs {}|]
