{-# LANGUAGE QuasiQuotes #-}
{-# LANGUAGE TemplateHaskellQuotes #-}

-- | Copyright : (c) Crown Copyright GCHQ
module Bootstrap.Nix.Expr.Nixpkgs (nixpkgsBinding, nixpkgsExpr) where

import Bootstrap.Nix.Expr (Binding, Expr, nix, nixproperty, (|=))

-- | nixpkgs = `nixpkgsExpr`;
nixpkgsBinding :: Binding
nixpkgsBinding = [nixproperty|nixpkgs|] |= nixpkgsExpr

-- | An expression which imports nixpkgs from the flake.lock generated by the intermediate flake
nixpkgsExpr :: Expr
nixpkgsExpr =
  [nix|
  let lock = builtins.fromJSON (builtins.readFile ./flake.lock);
  in import (builtins.fetchTarball {
    url = "https://github.com/NixOS/nixpkgs/tarball/${lock.nodes.nixpkgs-src.locked.rev}";
    sha256 = lock.nodes.nixpkgs-src.locked.narHash;
  }) {}|]
